version: '3.1'
services:
    
  ditre: 
    image: ngthminhdev/devops-ditre:${TAG}
    build: ./ditre
    hostname: ditre
    networks:
      - team3_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ditre"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1s

  ditre2: 
    image: ngthminhdev/devops-ditre:${TAG}
    build: ./ditre
    hostname: ditre2
    networks:
      - team3_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://ditre"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1s

  bangphongthan: 
    image: ngthminhdev/devops-bangphongthan:${TAG}
    build: ./bangphongthan
    hostname: bangphongthan
    networks:
      - team3_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://bangphongthan"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1s

  bangphongthan2: 
    image: ngthminhdev/devops-bangphongthan:${TAG}
    build: ./bangphongthan
    hostname: bangphongthan2
    networks:
      - team3_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://bangphongthan"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 1s

  db:
    image: mariadb:11.3
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=team3
    volumes:
      - team3_db_volume:/var/lib/mysql
    networks:
      - team3_network
      
      
  backend:
    scale: 2
    hostname: backend
    image: ngthminhdev/devops-backend:${TAG}
    build: ./backend
    networks:
      - team3_network
  
  backend2:
    scale: 2
    hostname: backend2
    image: ngthminhdev/devops-backend:${TAG}
    build: ./backend
    networks:
      - team3_network

    
  nginx:
    image: ngthminhdev/devops-nginx:${TAG}
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      ditre:
        condition: service_healthy
      bangphongthan:
        condition: service_healthy
      # backend:
        # condition: service_healthy
      # db:
        # condition: service_healthy

    networks:
      - team3_network

networks:
  team3_network:

volumes:
  team3_db_volume:
