FROM nginx:1.21.6-alpine
COPY ditre.conf /etc/nginx/conf.d/ditre.conf
COPY bangphongthan.conf /etc/nginx/conf.d/bangphongthan.conf
COPY api.conf /etc/nginx/conf.d/api.conf

# COPY nginx.conf /etc/nginx/nginx.conf